CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    likes INTEGER NOT NULL,
    postid TEXT NOT NULL,
    imageurl TEXT NOT NULL,
    image BLOB NOT NULL,
    timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);